### ISSUE TITLE
Failed to connect to bahai-browser.org

### ISSUE THREAD

**Issue by azatserzhan** [dragfyre/bahai-date-api#36]
Allahu - Abha friends, when I try get "today" or "date", server send me error:
Error: connect ENETUNREACH 71.19.146.123:443

**Comment by brettz9** [comment]
I'm afraid that I'm out of the country and I don't know how to confirm here whether I am currently unable to login to bahai-browser.org due to the country blocking ssh connections or due to a problem with my service. So, unfortunately, as far as I can see, this problem could be existing for at least another month or so.

**Comment by brettz9** [comment]
I've thankfully been able to confirm that the issue is probably on my account's end, so hopefully I will be able to get an answer for this from my service provider.

**Comment by brettz9** [comment]
This should now be working as I've gotten my service restored. Feel free to comment further if there are still issues.
